name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ci-ubuntu:
    strategy:
      matrix:
        version: [22]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ matrix.version }}

      - run: |
          git clone https://github.com/emscripten-core/emsdk.git /tmp/emsdk
          /tmp/emsdk/emsdk install latest
          /tmp/emsdk/emsdk activate latest
        name: Setup emcc

      - run: npm ci

      - run: |
          export PATH=$PATH:/tmp/emsdk:/tmp/emsdk/upstream/emscripten
          npm run build-wasm
        working-directory: l10n-dev
        name: Compile wasm binaries
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        name: upload tree-sitter-tsx.wasm
        with:
          name: tree-sitter-tsx.wasm
          path: l10n-dev/src/ast/tree-sitter-tsx.wasm
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        name: upload tree-sitter-typescript.wasm
        with:
          name: tree-sitter-typescript.wasm
          path: l10n-dev/src/ast/tree-sitter-typescript.wasm

      - run: npm test

  ci-windows:
    needs: ci-ubuntu
    strategy:
      matrix:
        version: [22]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ matrix.version }}

      - run: npm ci

      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        name: download tree-sitter-tsx.wasm
        with:
          name: tree-sitter-tsx.wasm
          path: l10n-dev/src/ast
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        name: download tree-sitter-typescript.wasm
        with:
          name: tree-sitter-typescript.wasm
          path: l10n-dev/src/ast

      - run: npm test
