name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ci:
    strategy:
      matrix:
        version: [14, 16]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.version }}

      # From https://github.com/actions/setup-node/issues/68#issuecomment-536238341
      - name: patch node gyp on windows to support Visual Studio 2019
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          npm install --global node-gyp@latest
          npm prefix -g | % {npm config set node_gyp "$_\node_modules\node-gyp\bin\node-gyp.js"}
          
      - run: npm ci
      - run: npm test
