name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ci-ubuntu:
    strategy:
      matrix:
        version: [18]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.version }}

      - run: |
          git clone https://github.com/emscripten-core/emsdk.git /tmp/emsdk
          /tmp/emsdk/emsdk install latest
          /tmp/emsdk/emsdk activate latest
        name: Setup emcc

      - run: npm ci

      - run: |
          export PATH=$PATH:/tmp/emsdk:/tmp/emsdk/upstream/emscripten
          npm run build-wasm
        working-directory: l10n-dev
        name: Compile wasm binaries
      - uses: actions/upload-artifact@v3
        name: upload tree-sitter-tsx.wasm
        with:
          name: tree-sitter-tsx.wasm
          path: l10n-dev/src/ast/tree-sitter-tsx.wasm
      - uses: actions/upload-artifact@v3
        name: upload tree-sitter-typescript.wasm
        with:
          name: tree-sitter-typescript.wasm
          path: l10n-dev/src/ast/tree-sitter-typescript.wasm

      - run: npm test

  ci-windows:
    needs: ci-ubuntu
    strategy:
      matrix:
        version: [18]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.version }}

      - run: npm ci

      - uses: actions/download-artifact@v3
        name: download tree-sitter-tsx.wasm
        with:
          name: tree-sitter-tsx.wasm
          path: l10n-dev/src/ast
      - uses: actions/download-artifact@v3
        name: download tree-sitter-typescript.wasm
        with:
          name: tree-sitter-typescript.wasm
          path: l10n-dev/src/ast

      - run: npm test
